/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import clases.Administracion;
import clases.DaoAdministracion;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * /**
 *
 * @author Juan Pablo Vazquez Ruiz el frame contiene todas las invocaciones de
 * metodos para el Frame Administracion.
 */
public class frmAdministracion extends javax.swing.JFrame {
    int buscar = 0;
    private void skin() {
        Font textTitulo = new Font("Tahoma", Font.BOLD, 24);
        Font textComponente = new Font("Tahoma", Font.BOLD, 14);
        lblAdministracion.setFont(textTitulo);
        lblMedioAdministracion.setFont(textComponente);
        txtMedioAdministracion.setFont(textComponente);
        btnAgregar.setFont(textComponente);
        btnBuscar.setFont(textComponente);
        btnEliminar.setFont(textComponente);
        btnListarParecidos.setFont(textComponente);
        btnModificar.setFont(textComponente);
        btnRegresar.setFont(textComponente);
    }

    /**
     * Creates new form frmAdministracion
     */
    public frmAdministracion() {
        initComponents();
        skin();
        DaoAdministracion da = new DaoAdministracion();
        da.setAdministracion(txtMedioAdministracion.getText());
        tblAdministracion.setModel(da.listar());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdministracion = new javax.swing.JLabel();
        lblMedioAdministracion = new javax.swing.JLabel();
        txtMedioAdministracion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdministracion = new javax.swing.JTable();
        btnListarParecidos = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdministracion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAdministracion.setText("ADMINISTRACION");
        getContentPane().add(lblAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 11, -1, -1));

        lblMedioAdministracion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMedioAdministracion.setText("MEDIO DE ADMINISTRACION");
        getContentPane().add(lblMedioAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 92, -1, -1));

        txtMedioAdministracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedioAdministracionKeyReleased(evt);
            }
        });
        getContentPane().add(txtMedioAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 130, -1));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 359, -1, 40));
        btnAgregar.getAccessibleContext().setAccessibleName("");

        btnModificar.setText("MODIFICAR");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, 40));
        btnModificar.getAccessibleContext().setAccessibleName("");

        btnEliminar.setText("ELIMINAR");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, 40));
        btnEliminar.getAccessibleContext().setAccessibleName("");

        tblAdministracion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAdministracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdministracionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAdministracion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 126, 553, 222));

        btnListarParecidos.setText("LISTAR PARECIDOS");
        btnListarParecidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarParecidosActionPerformed(evt);
            }
        });
        getContentPane().add(btnListarParecidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 80, -1, 40));

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 359, -1, 40));
        btnRegresar.getAccessibleContext().setAccessibleName("");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, 40));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Administracion a1 = new Administracion();
        DaoAdministracion da = new DaoAdministracion();

        da.setAdministracion(txtMedioAdministracion.getText());

        if (da.agregar() == true) {
            JOptionPane.showMessageDialog(rootPane, "Registro agregado");
            txtMedioAdministracion.setText("");
            btnListarParecidos.doClick();

        } else {
            JOptionPane.showMessageDialog(rootPane, "No se inserto");

        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Administracion a2 = new Administracion();
        DaoAdministracion da1 = new DaoAdministracion();
        da1.setIdAdministracion(buscar);
        da1.setAdministracion(txtMedioAdministracion.getText());

        if (da1.modificar()) {
            JOptionPane.showMessageDialog(rootPane, "se ha modificado el registro");
            txtMedioAdministracion.setText("");
            btnListarParecidos.doClick();
            btnEliminar.setEnabled(false);
            btnModificar.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(rootPane, "No se modifico");
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Administracion a3 = new Administracion();
        DaoAdministracion da = new DaoAdministracion();
        da.setAdministracion(txtMedioAdministracion.getText());
        if (da.eliminar() == true) {
            JOptionPane.showMessageDialog(rootPane, "Se elimino el registro");
            txtMedioAdministracion.setText("");
            btnListarParecidos.doClick();
            btnEliminar.setEnabled(false);
            btnModificar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se elimino el registro");
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DaoAdministracion d5 = new DaoAdministracion();
        d5.setAdministracion(txtMedioAdministracion.getText());
        if (d5.buscar()) {
            buscar = d5.getIdAdministracion();
            txtMedioAdministracion.setText(d5.getAdministracion());
            JOptionPane.showMessageDialog(rootPane, "El producto existe");
            btnEliminar.setEnabled(true);
            btnModificar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Producto no encontrado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListarParecidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarParecidosActionPerformed
        DaoAdministracion da = new DaoAdministracion();
        da.setAdministracion(txtMedioAdministracion.getText());
        txtMedioAdministracion.setText("");
        tblAdministracion.setModel(da.listar());
    }//GEN-LAST:event_btnListarParecidosActionPerformed

    private void tblAdministracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdministracionMouseClicked
        int filaSeleccionada = tblAdministracion.getSelectedRow();
        int columna = 0;
        buscar = Integer.parseInt((String) tblAdministracion.getValueAt(filaSeleccionada, columna));
        txtMedioAdministracion.setText((String) tblAdministracion.getModel().getValueAt(filaSeleccionada, columna + 1));
        btnEliminar.setEnabled(true);
        btnModificar.setEnabled(true);
    }//GEN-LAST:event_tblAdministracionMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        frmProducto fp = new frmProducto();
        fp.setVisible(true);

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtMedioAdministracionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedioAdministracionKeyReleased
        txtMedioAdministracion.setText(txtMedioAdministracion.getText().toUpperCase());
    }//GEN-LAST:event_txtMedioAdministracionKeyReleased

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdministracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListarParecidos;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdministracion;
    private javax.swing.JLabel lblMedioAdministracion;
    private javax.swing.JTable tblAdministracion;
    private javax.swing.JTextField txtMedioAdministracion;
    // End of variables declaration//GEN-END:variables
}
