/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import clases.Conex;
import clases.DaoCompra;
import clases.DaoDetalleEntrada;
import java.awt.Font;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sonny
 */
public class frmEntrada extends javax.swing.JFrame {

    private void skin() {
        Font textTitulo = new Font("Tahoma", Font.BOLD, 24);
        Font textComponente = new Font("Tahoma", Font.BOLD, 14);
        lblEntrada.setFont(textTitulo);
        lblCantidad.setFont(textComponente);
        lblCaducidad.setFont(textComponente);
        lblProductos.setFont(textComponente);
        txtCaducidad.setFont(textComponente);
        txtCantidad.setFont(textComponente);
        btnAceptar.setFont(textComponente);
        btnCancelar.setFont(textComponente);
    }

    /**
     * Creates new form frmEntrada
     */
    public frmEntrada() {
        initComponents();
        skin();
        CargacomboProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEntrada = new javax.swing.JLabel();
        cmbProductos = new javax.swing.JComboBox();
        lblCantidad = new javax.swing.JLabel();
        lblCaducidad = new javax.swing.JLabel();
        rbtAsignado = new javax.swing.JRadioButton();
        rbtDonado = new javax.swing.JRadioButton();
        rbtComprado = new javax.swing.JRadioButton();
        txtCantidad = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblProductos = new javax.swing.JLabel();
        txtCaducidad = new com.toedter.calendar.JDateChooser();
        txtFarmacia = new javax.swing.JTextField();
        txtNoFactura = new javax.swing.JTextField();
        txtCosto = new javax.swing.JFormattedTextField();
        lblCosto = new javax.swing.JLabel();
        lblFarmacia = new javax.swing.JLabel();
        lblNoFactura = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEntrada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEntrada.setText("ENTRADA");
        getContentPane().add(lblEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 31, -1, -1));

        cmbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductosActionPerformed(evt);
            }
        });
        getContentPane().add(cmbProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 61, 180, -1));

        lblCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCantidad.setText("CANTIDAD");
        getContentPane().add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 92, -1, -1));

        lblCaducidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCaducidad.setText("CADUCIDAD");
        getContentPane().add(lblCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 123, -1, -1));

        rbtAsignado.setText("ASIGNADO");
        rbtAsignado.setContentAreaFilled(false);
        rbtAsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAsignadoActionPerformed(evt);
            }
        });
        getContentPane().add(rbtAsignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 158, -1, -1));

        rbtDonado.setText("DONADO");
        rbtDonado.setContentAreaFilled(false);
        rbtDonado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDonadoActionPerformed(evt);
            }
        });
        getContentPane().add(rbtDonado, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 158, -1, -1));

        rbtComprado.setText("COMPRADO");
        rbtComprado.setContentAreaFilled(false);
        rbtComprado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCompradoActionPerformed(evt);
            }
        });
        getContentPane().add(rbtComprado, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 158, -1, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 92, 100, -1));

        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 337, -1, 40));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 337, -1, 40));

        lblProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProductos.setText("PRODUCTOS");
        getContentPane().add(lblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 61, -1, -1));
        getContentPane().add(txtCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, -1));

        txtFarmacia.setEditable(false);
        txtFarmacia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFarmaciaKeyReleased(evt);
            }
        });
        getContentPane().add(txtFarmacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 90, -1));

        txtNoFactura.setEditable(false);
        getContentPane().add(txtNoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 90, -1));

        txtCosto.setEditable(false);
        txtCosto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 90, -1));

        lblCosto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCosto.setText("COSTO");
        getContentPane().add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        lblFarmacia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFarmacia.setText("FARMACIA");
        getContentPane().add(lblFarmacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        lblNoFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNoFactura.setText("No. FACTURA");
        getContentPane().add(lblNoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        btnGenerarReporte.setText("GENERAR REPORTE");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        DaoDetalleEntrada de = new DaoDetalleEntrada();
        int idProd = 0;
        DateFormat fmt = new SimpleDateFormat("yy/MM/dd");

        if (rbtAsignado.isSelected()) {
            String prod = cmbProductos.getSelectedItem().toString();
            de.setEntrada(Integer.parseInt(txtCantidad.getText()));
            String date = fmt.format(txtCaducidad.getDate());
            de.setCaducidad(date);
            de.setTipoEntrada("ASIGNADO");
            Connection con = Conex.getInstance().getConnection();
            String sql = "{call sp_prod_lis(?)}";
            try {
                CallableStatement stm = con.prepareCall(sql);
                stm.setString(1, prod);
                ResultSet rs = stm.executeQuery();
                if (rs.next()) {
                    idProd = rs.getInt("idProducto");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            de.setIdProducto(idProd);
            if ((de.agregar2()) == true) {
                JOptionPane.showMessageDialog(rootPane, "Registro agregado");
                txtCantidad.setText("");
//            txtCaducidad.setDate("");
                CargacomboProducto();

            } else {
                JOptionPane.showMessageDialog(rootPane, "No se inserto");

            }
        } else if (rbtComprado.isSelected()) {
            DaoCompra dc = new DaoCompra();
            dc.setFarmacia(txtFarmacia.getText());
            dc.setNumFactura(txtNoFactura.getText());
            dc.setCosto(Double.parseDouble(txtCosto.getText()));
            if (dc.agregar() == true) {

                txtFarmacia.setText("");
                txtNoFactura.setText("");
                txtCosto.setText("");

            } else {
                JOptionPane.showMessageDialog(rootPane, "No se inserto");

            }
            String prod = cmbProductos.getSelectedItem().toString();
            de.setEntrada(Integer.parseInt(txtCantidad.getText()));
            String date = fmt.format(txtCaducidad.getDate());
            de.setCaducidad(date);
            de.setTipoEntrada("COMPRADO");
            Connection con = Conex.getInstance().getConnection();
            String sql = "{call sp_prod_lis(?)}";
            try {
                CallableStatement stm = con.prepareCall(sql);
                stm.setString(1, prod);
                ResultSet rs = stm.executeQuery();
                if (rs.next()) {
                    idProd = rs.getInt("idProducto");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            de.setIdProducto(idProd);
            if ((de.agregar()) == true) {
                JOptionPane.showMessageDialog(rootPane, "Registro agregado");
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se inserto");
            }
            txtCantidad.setText("");
            CargacomboProducto();

        } else if (rbtDonado.isSelected()) {
            String prod = cmbProductos.getSelectedItem().toString();
            de.setEntrada(Integer.parseInt(txtCantidad.getText()));
            String date = fmt.format(txtCaducidad.getDate());
            de.setCaducidad(date);
            de.setTipoEntrada("DONADO");
            Connection con = Conex.getInstance().getConnection();
            String sql = "{call sp_prod_lis(?)}";
            try {
                CallableStatement stm = con.prepareCall(sql);
                stm.setString(1, prod);
                ResultSet rs = stm.executeQuery();
                if (rs.next()) {
                    idProd = rs.getInt("idProducto");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            de.setIdProducto(idProd);

            if ((de.agregar2()) == true) {
                JOptionPane.showMessageDialog(rootPane, "Registro agregado");
                txtCantidad.setText("");
//            txtCaducidad.setDate("");
                CargacomboProducto();

            } else {
                JOptionPane.showMessageDialog(rootPane, "No se inserto");

            }

        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductosActionPerformed

    private void rbtAsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtAsignadoActionPerformed
        if (rbtAsignado.isSelected()) {
            rbtComprado.setSelected(false);
            rbtDonado.setSelected(false);
            txtFarmacia.setEditable(false);
            txtCosto.setEditable(false);
            txtNoFactura.setEditable(false);
            txtCosto.setText("");
        }
    }//GEN-LAST:event_rbtAsignadoActionPerformed

    private void rbtDonadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDonadoActionPerformed
        if (rbtDonado.isSelected()) {
            rbtComprado.setSelected(false);
            rbtAsignado.setSelected(false);
            txtFarmacia.setEditable(false);
            txtCosto.setEditable(false);
            txtNoFactura.setEditable(false);
            txtCosto.setText("");
        }
    }//GEN-LAST:event_rbtDonadoActionPerformed

    private void rbtCompradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCompradoActionPerformed
        if (rbtComprado.isSelected()) {
            rbtAsignado.setSelected(false);
            rbtDonado.setSelected(false);
            txtFarmacia.setEditable(true);
            txtCosto.setEditable(true);
            txtNoFactura.setEditable(true);
        }
    }//GEN-LAST:event_rbtCompradoActionPerformed

    private void txtFarmaciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFarmaciaKeyReleased
        txtFarmacia.setText(txtFarmacia.getText().toUpperCase());
    }//GEN-LAST:event_txtFarmaciaKeyReleased

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        pantallas.frmReporteCompra frc = new pantallas.frmReporteCompra();
        frc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void CargacomboProducto() {
        Connection con = Conex.getInstance().getConnection();
               String sql = "{call sp_prod_sel ()}";
               cmbProductos.removeAllItems();
            try {
                CallableStatement stm = con.prepareCall(sql);
                ResultSet rs = stm.executeQuery();
            while (rs.next()) {
                cmbProductos.addItem(rs.getString("nombreProductoPat"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JComboBox cmbProductos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCaducidad;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblFarmacia;
    private javax.swing.JLabel lblNoFactura;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JRadioButton rbtAsignado;
    private javax.swing.JRadioButton rbtComprado;
    private javax.swing.JRadioButton rbtDonado;
    private com.toedter.calendar.JDateChooser txtCaducidad;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JFormattedTextField txtCosto;
    private javax.swing.JTextField txtFarmacia;
    private javax.swing.JTextField txtNoFactura;
    // End of variables declaration//GEN-END:variables
}
