/*
 * Nombre del autor: Iván Ruiz Ramírez
                     Jose Luis Terraza Cortés
                     Dámaso Valdés Rosales
 * Fecha de creación: 2017/01/31
 * Nombre del proyecto: casaDescanso
 * Nombre del módulo: centralDeEnfermería
 * Breve descripción del contenido: El frame "frmEnfermeras" contempla los datos del personal de enfermería,
 * el cual permite realizar altas,bajas,cambios a la base de datos y mostrar la lista del personal.
 */
package pantallas;

import clases.DAOEnfermeras;
import static pantallas.frmMenuCentEnf.menuP;
import java.awt.Font;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class frmEnfermeras extends javax.swing.JFrame {

    /**
     *
     */
    
    Font textoTitulos = new Font("Tahoma",Font.BOLD,24);
    Font textoComponentes = new Font("Tahoma",Font.BOLD,14);
            
    public frmEnfermeras() {
        initComponents();
        skin1();
    }
    static frmListEnf listEnf = new frmListEnf();
    static frmEnfermeras frmEnf = new frmEnfermeras();
    
    public void skin1(){
        lblNombreEnfermera.setText(lblNombreEnfermera.getText().toUpperCase());
        lblApellidoMatEnf.setText(lblApellidoMatEnf.getText().toUpperCase());
        lblApellidoPatEnf.setText(lblApellidoPatEnf.getText().toUpperCase());
        lblBuscarEliminarModificar.setText(lblBuscarEliminarModificar.getText().toUpperCase());
        lblRegistroDePersonal.setText(lblRegistroDePersonal.getText().toUpperCase());
        lblEspecialidad.setText(lblEspecialidad.getText().toUpperCase());
        lblTipoDeIngreso.setText(lblTipoDeIngreso.getText().toUpperCase());
        lblEstatus.setText(lblEstatus.getText().toUpperCase());
        lblDescrEstatus.setText(lblDescrEstatus.getText().toUpperCase());
        lblTelefonoEnf.setText(lblTelefonoEnf.getText().toUpperCase());
        lblCorreoEnf.setText(lblCorreoEnf.getText().toUpperCase());
        lblFechaIn.setText(lblFechaIn.getText().toUpperCase());
        lblFechaTerm.setText(lblFechaTerm.getText().toUpperCase());
        btnAgregarEnf.setText(btnAgregarEnf.getText().toUpperCase());
        btnModificarEnf.setText(btnModificarEnf.getText().toUpperCase());
        btnEliminarEnf.setText(btnEliminarEnf.getText().toUpperCase());
        btnListaPersonalEnf.setText(btnListaPersonalEnf.getText().toUpperCase());
        btnRegresar.setText(btnRegresar.getText().toUpperCase());
        btnAgregarEnf.setSize(71,40);
        btnModificarEnf.setSize(71,40);
        btnEliminarEnf.setSize(71,40);
        btnListaPersonalEnf.setSize(71,40);
        btnRegresar.setSize(71,40);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistroDePersonal = new javax.swing.JLabel();
        lblIdEnfermera = new javax.swing.JLabel();
        lblNombreEnfermera = new javax.swing.JLabel();
        lblApellidoPatEnf = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        lblTelefonoEnf = new javax.swing.JLabel();
        lblCorreoEnf = new javax.swing.JLabel();
        lblTipoDeIngreso = new javax.swing.JLabel();
        txtIdEnfermera = new javax.swing.JTextField();
        txtNombreEnfermera = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();
        txtCorreoEnf = new javax.swing.JTextField();
        txtEstatus = new javax.swing.JTextField();
        btnAgregarEnf = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnModificarEnf = new javax.swing.JButton();
        btnEliminarEnf = new javax.swing.JButton();
        btnListaPersonalEnf = new javax.swing.JButton();
        lblBuscarEliminarModificar = new javax.swing.JLabel();
        lblDescrEstatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescrEstatus = new javax.swing.JTextArea();
        lblEstatus = new javax.swing.JLabel();
        txtApellidoPatEnf = new javax.swing.JTextField();
        txtApellidoMatEnf = new javax.swing.JTextField();
        lblApellidoMatEnf = new javax.swing.JLabel();
        ftfTelefonoEnf = new javax.swing.JFormattedTextField();
        lblFechaIn = new javax.swing.JLabel();
        lblFechaTerm = new javax.swing.JLabel();
        cmbTipoDeIngreso = new javax.swing.JComboBox<>();
        dchFechaIn = new com.toedter.calendar.JDateChooser();
        dchFechaTerm = new com.toedter.calendar.JDateChooser();
        lblFondoVerde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistroDePersonal.setFont(textoTitulos);
        lblRegistroDePersonal.setText("Registro de personal");
        getContentPane().add(lblRegistroDePersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 25, -1, 52));

        lblIdEnfermera.setFont(textoComponentes);
        lblIdEnfermera.setText("ID:");
        getContentPane().add(lblIdEnfermera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, -1, -1));

        lblNombreEnfermera.setFont(textoComponentes);
        lblNombreEnfermera.setText("Nombre(s):");
        getContentPane().add(lblNombreEnfermera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, -1, -1));

        lblApellidoPatEnf.setFont(textoComponentes);
        lblApellidoPatEnf.setText("Apellido Paterno:");
        getContentPane().add(lblApellidoPatEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 219, -1, -1));

        lblEspecialidad.setFont(textoComponentes);
        lblEspecialidad.setText("Especialidad:");
        getContentPane().add(lblEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 321, -1, -1));

        lblTelefonoEnf.setFont(textoComponentes);
        lblTelefonoEnf.setText("Telefono:");
        getContentPane().add(lblTelefonoEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        lblCorreoEnf.setFont(textoComponentes);
        lblCorreoEnf.setText("Correo:");
        getContentPane().add(lblCorreoEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        lblTipoDeIngreso.setFont(textoComponentes);
        lblTipoDeIngreso.setText("Tipo de ingreso:");
        getContentPane().add(lblTipoDeIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 385, 140, -1));

        txtIdEnfermera.setFont(textoComponentes);
        txtIdEnfermera.setEnabled(false);
        getContentPane().add(txtIdEnfermera, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 107, 110, 34));

        txtNombreEnfermera.setFont(textoComponentes);
        getContentPane().add(txtNombreEnfermera, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 173, 36));

        txtEspecialidad.setFont(textoComponentes);
        getContentPane().add(txtEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 173, 36));

        txtCorreoEnf.setFont(textoComponentes);
        txtCorreoEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoEnfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreoEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 200, 36));

        txtEstatus.setFont(textoComponentes);
        getContentPane().add(txtEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 210, 36));

        btnAgregarEnf.setFont(textoComponentes);
        btnAgregarEnf.setText("Agregar");
        btnAgregarEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEnfActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 539, 140, 40));

        btnRegresar.setFont(textoComponentes);
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 539, 140, 40));

        btnModificarEnf.setFont(textoComponentes);
        btnModificarEnf.setText("Modificar");
        btnModificarEnf.setEnabled(false);
        btnModificarEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEnfActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 539, 145, 40));

        btnEliminarEnf.setFont(textoComponentes);
        btnEliminarEnf.setText("Eliminar");
        btnEliminarEnf.setEnabled(false);
        btnEliminarEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEnfActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 539, 145, 40));

        btnListaPersonalEnf.setFont(textoComponentes);
        btnListaPersonalEnf.setText("Lista de personal");
        btnListaPersonalEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaPersonalEnfActionPerformed(evt);
            }
        });
        getContentPane().add(btnListaPersonalEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 539, 200, 40));

        lblBuscarEliminarModificar.setFont(textoComponentes);
        lblBuscarEliminarModificar.setText("(Buscar/Eliminar/Modificar) ");
        getContentPane().add(lblBuscarEliminarModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 117, -1, -1));

        lblDescrEstatus.setFont(textoComponentes);
        lblDescrEstatus.setText("Descripción Estatus:");
        getContentPane().add(lblDescrEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 189, -1));

        txaDescrEstatus.setColumns(20);
        txaDescrEstatus.setFont(textoComponentes);
        txaDescrEstatus.setRows(5);
        jScrollPane1.setViewportView(txaDescrEstatus);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 293, 120));

        lblEstatus.setFont(textoComponentes);
        lblEstatus.setText("Estatus:");
        getContentPane().add(lblEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 70, -1));

        txtApellidoPatEnf.setFont(textoComponentes);
        getContentPane().add(txtApellidoPatEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 173, 30));

        txtApellidoMatEnf.setFont(textoComponentes);
        getContentPane().add(txtApellidoMatEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 256, 173, 30));

        lblApellidoMatEnf.setFont(textoComponentes);
        lblApellidoMatEnf.setText("Apellido Materno:");
        getContentPane().add(lblApellidoMatEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, -1, -1));

        try {
            ftfTelefonoEnf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfTelefonoEnf.setFont(textoComponentes);
        ftfTelefonoEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfTelefonoEnfActionPerformed(evt);
            }
        });
        getContentPane().add(ftfTelefonoEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 200, 36));

        lblFechaIn.setFont(textoComponentes);
        lblFechaIn.setText("Fecha inicio:");
        getContentPane().add(lblFechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 454, 126, -1));

        lblFechaTerm.setFont(textoComponentes);
        lblFechaTerm.setText("Fecha terminacion:");
        getContentPane().add(lblFechaTerm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 486, 170, -1));

        cmbTipoDeIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PASANTE/SERVICIO SOCIAL", "ENFERMERO/ENFERMERA" }));
        cmbTipoDeIngreso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoDeIngresoItemStateChanged(evt);
            }
        });
        cmbTipoDeIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoDeIngresoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipoDeIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 378, 230, 28));

        dchFechaIn.setFont(textoComponentes);
        getContentPane().add(dchFechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 168, -1));

        dchFechaTerm.setFont(textoComponentes);
        getContentPane().add(dchFechaTerm, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 486, 168, -1));

        lblFondoVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(lblFondoVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEnfActionPerformed
        DateFormat fmt = new SimpleDateFormat("yy/MM/dd");
        String dateIn="";
        String dateTerm="";
        if(!cmbTipoDeIngreso.getSelectedItem().toString().equals("ENFERMERO/ENFERMERA")){
            if (dchFechaIn.getDate() == null || dchFechaTerm.getDate() == null) {
                JOptionPane.showMessageDialog(null, "El campo de la fecha de inicio y fecha de terminación no pueden estar vacíos.");
            }
            else{
                dateIn = fmt.format(dchFechaIn.getDate());
                dateTerm = fmt.format(dchFechaTerm.getDate());
            }
        }
        else{
            dateIn = null;
            dateTerm = null;
        }
        
        if (txtNombreEnfermera.getText().equals("") || txtApellidoMatEnf.getText().equals("") || txtApellidoPatEnf.getText().equals("") || txtApellidoMatEnf.getText().equals("") || txtEspecialidad.getText().equals("") || txtEstatus.getText().equals("") || ftfTelefonoEnf.getText().equals("") || txtCorreoEnf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campos vacíos.");
        } else {
            DAOEnfermeras daoEnf = new DAOEnfermeras(Integer.parseInt(txtIdEnfermera.getText()), txtNombreEnfermera.getText().toUpperCase(), txtApellidoPatEnf.getText().toUpperCase(), txtApellidoMatEnf.getText().toUpperCase(), txtEspecialidad.getText().toUpperCase(), cmbTipoDeIngreso.getSelectedItem().toString().toUpperCase(), dateIn, dateTerm, txtEstatus.getText().toUpperCase(), txaDescrEstatus.getText().toUpperCase(), ftfTelefonoEnf.getText(), txtCorreoEnf.getText().toUpperCase(),"");
            if(!txtCorreoEnf.getText().matches("[-\\w\\.]+@\\w+\\.\\w+")){
                JOptionPane.showMessageDialog(null,"El campo de correo electrónico debe ser: cualquierCosa@ServicioDeCorreo.[com/net/etc] ");
            }
            else{
                if (daoEnf.modificar()) {
                    JOptionPane.showMessageDialog(null, "El nuevo personal de enfermeria fue modificado.");
                    txtIdEnfermera.setText("");
                    txtNombreEnfermera.setText("");
                    txtApellidoPatEnf.setText("");
                    txtApellidoMatEnf.setText("");
                    txtEspecialidad.setText("");
                    txtEstatus.setText("");
                    txaDescrEstatus.setText("");
                    ftfTelefonoEnf.setText("");
                    txtCorreoEnf.setText("");
                    dchFechaIn.setCalendar(null);
                    dchFechaTerm.setCalendar(null);
                    btnModificarEnf.setEnabled(false);
                    btnEliminarEnf.setEnabled(false);
                    btnAgregarEnf.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, daoEnf.getMensaje());
                }
            }
        }
    }//GEN-LAST:event_btnModificarEnfActionPerformed

    private void txtCorreoEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoEnfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoEnfActionPerformed

    private void btnEliminarEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEnfActionPerformed
        DAOEnfermeras daoEnf = new DAOEnfermeras();
        daoEnf.setIdEnfermera(Integer.parseInt(txtIdEnfermera.getText()));
        daoEnf.eliminar();
        JOptionPane.showMessageDialog(null,"El personal de enfermeria fue eliminado.");
        txtIdEnfermera.setText("");
        txtNombreEnfermera.setText("");
        txtApellidoPatEnf.setText("");
        txtApellidoMatEnf.setText("");
        txtEspecialidad.setText("");
        txtEstatus.setText("");
        txaDescrEstatus.setText("");
        ftfTelefonoEnf.setText("");
        txtCorreoEnf.setText("");
        dchFechaIn.setCalendar(null);
        dchFechaTerm.setCalendar(null);
        btnEliminarEnf.setEnabled(false);
        btnModificarEnf.setEnabled(false);
        btnAgregarEnf.setEnabled(true);

    }//GEN-LAST:event_btnEliminarEnfActionPerformed

    private void btnAgregarEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEnfActionPerformed
        DateFormat fmt = new SimpleDateFormat("yy/MM/dd");
        String dateIn="";
        String dateTerm="";
        if(!cmbTipoDeIngreso.getSelectedItem().toString().equals("ENFERMERO/ENFERMERA")){
            if (dchFechaIn.getDate() == null || dchFechaTerm.getDate() == null) {
                JOptionPane.showMessageDialog(null, "El campo de la fecha de inicio y fecha de terminación no pueden estar vacíos.");
            }
            else{
                dateIn = fmt.format(dchFechaIn.getDate());
                dateTerm = fmt.format(dchFechaTerm.getDate());
            }
        }
        else{
            dateIn = null;
            dateTerm = null;
        }
        
        if (txtNombreEnfermera.getText().equals("") || txtApellidoMatEnf.getText().equals("") || txtApellidoPatEnf.getText().equals("") || txtApellidoMatEnf.getText().equals("") || txtEstatus.getText().equals("") || ftfTelefonoEnf.getText().equals("") || txtCorreoEnf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campos vacíos.");
        } else {
            if(!txtCorreoEnf.getText().matches("[-\\w\\.]+@\\w+\\.\\w+")){
                JOptionPane.showMessageDialog(null,"El campo de correo electrónico debe ser: cualquierCosa@ServicioDeCorreo.[com/net/etc] ");
            }
            else{
                DAOEnfermeras daoEnf = new DAOEnfermeras(0, txtNombreEnfermera.getText().toUpperCase(), txtApellidoPatEnf.getText().toUpperCase(), txtApellidoMatEnf.getText().toUpperCase(), txtEspecialidad.getText().toUpperCase(), cmbTipoDeIngreso.getSelectedItem().toString().toUpperCase(),dateIn, dateTerm, txtEstatus.getText().toUpperCase(), txaDescrEstatus.getText().toUpperCase(), ftfTelefonoEnf.getText(), txtCorreoEnf.getText().toUpperCase(),"");
                if (daoEnf.agregar()) {
                    JOptionPane.showMessageDialog(null, "El nuevo personal de enfermeria fue agregado.");
                    txtIdEnfermera.setText("");
                    txtNombreEnfermera.setText("");
                    txtApellidoPatEnf.setText("");
                    txtApellidoMatEnf.setText("");
                    txtEspecialidad.setText("");
                    txtEstatus.setText("");
                    txaDescrEstatus.setText("");
                    ftfTelefonoEnf.setText("");
                    txtCorreoEnf.setText("");
                    dchFechaIn.setCalendar(null);
                    dchFechaTerm.setCalendar(null);
                } else {
                    JOptionPane.showMessageDialog(null, daoEnf.getMensaje());
                }
            }
            
        }

    }//GEN-LAST:event_btnAgregarEnfActionPerformed

    private void ftfTelefonoEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfTelefonoEnfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfTelefonoEnfActionPerformed

    private void btnListaPersonalEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaPersonalEnfActionPerformed
        DAOEnfermeras daoEnf = new DAOEnfermeras();
        dispose();
        listEnf.setVisible(true);
        daoEnf.listar();
        listEnf.tblPersonalEnf.setModel(daoEnf.getTmodel());
    }//GEN-LAST:event_btnListaPersonalEnfActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
        //menuP.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cmbTipoDeIngresoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoDeIngresoItemStateChanged
        if(cmbTipoDeIngreso.getSelectedItem().toString().equals("ENFERMERO/ENFERMERA")){
            dchFechaIn.setEnabled(false);
            dchFechaTerm.setEnabled(false);
        }
        else{
            dchFechaIn.setEnabled(true);
            dchFechaTerm.setEnabled(true);
        }
    }//GEN-LAST:event_cmbTipoDeIngresoItemStateChanged

    private void cmbTipoDeIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoDeIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoDeIngresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEnfermeras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEnfermeras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEnfermeras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEnfermeras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEnfermeras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarEnf;
    public javax.swing.JButton btnEliminarEnf;
    private javax.swing.JButton btnListaPersonalEnf;
    public javax.swing.JButton btnModificarEnf;
    private javax.swing.JButton btnRegresar;
    public javax.swing.JComboBox<String> cmbTipoDeIngreso;
    public com.toedter.calendar.JDateChooser dchFechaIn;
    public com.toedter.calendar.JDateChooser dchFechaTerm;
    public javax.swing.JFormattedTextField ftfTelefonoEnf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidoMatEnf;
    private javax.swing.JLabel lblApellidoPatEnf;
    private javax.swing.JLabel lblBuscarEliminarModificar;
    private javax.swing.JLabel lblCorreoEnf;
    private javax.swing.JLabel lblDescrEstatus;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblFechaIn;
    private javax.swing.JLabel lblFechaTerm;
    private javax.swing.JLabel lblFondoVerde;
    private javax.swing.JLabel lblIdEnfermera;
    private javax.swing.JLabel lblNombreEnfermera;
    private javax.swing.JLabel lblRegistroDePersonal;
    private javax.swing.JLabel lblTelefonoEnf;
    private javax.swing.JLabel lblTipoDeIngreso;
    public javax.swing.JTextArea txaDescrEstatus;
    public javax.swing.JTextField txtApellidoMatEnf;
    public javax.swing.JTextField txtApellidoPatEnf;
    public javax.swing.JTextField txtCorreoEnf;
    public javax.swing.JTextField txtEspecialidad;
    public javax.swing.JTextField txtEstatus;
    public javax.swing.JTextField txtIdEnfermera;
    public javax.swing.JTextField txtNombreEnfermera;
    // End of variables declaration//GEN-END:variables
}
