/*
 * Nombre de los autores: Dámaso Valdés Rosales.
 * Fecha de creación: 15/03/2017.
 * Nombre del proyecto: casaDescanso
 * Nombre del módulo: centralDeEnfermería
 * Breve descripción del contenido:  Este es el frame de la clase Incidencias, aqui se listan las incidencias de los
 * pacientes cuando uno de sus datos es modificado.
 */
package pantallas;

import clases.DAORegistroSaludPac;
import java.awt.Dimension;
import java.awt.Font;
import static pantallas.frmxLogin.regSalud;

/**
 *
 * @author Damaso
 */
public class frmIncidencias extends javax.swing.JFrame {

    /**
     * Creates new form frmIncidencias
     */
    
    frmMenuCentEnf frmMenEnf = new frmMenuCentEnf();
    DAORegistroSaludPac daoReg = new DAORegistroSaludPac();
    
    public frmIncidencias() {
        initComponents();
        btnListar.doClick();
        skin1();
    }
    
    Font textoTitulos = new Font("Tahoma",Font.BOLD,24);
    Font textoComponentes = new Font("Tahoma",Font.BOLD,14);
    
    public void skin1(){
        Dimension dmnBtn = new Dimension(130, 40); //130, 50
        btnRegresar.setSize(dmnBtn);
        lblIncCenEnf.setText(lblIncCenEnf.getText().toUpperCase());
        lblPaciente.setText(lblPaciente.getText().toUpperCase());
        btnRegresar.setText(btnRegresar.getText().toUpperCase());
        btnListar.setText(btnListar.getText().toUpperCase());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIncCenEnf = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIncidencias = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        lblFondoVerde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIncCenEnf.setFont(textoTitulos);
        lblIncCenEnf.setText("Incidencias Central de Enfermeria");
        getContentPane().add(lblIncCenEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblPaciente.setFont(textoComponentes);
        lblPaciente.setText("Paciente");
        getContentPane().add(lblPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        txtPaciente.setFont(textoComponentes);
        txtPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteActionPerformed(evt);
            }
        });
        txtPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPacienteKeyReleased(evt);
            }
        });
        getContentPane().add(txtPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 52, 137, -1));

        tblIncidencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIncidencias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 786, 239));

        btnRegresar.setFont(textoComponentes);
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 353, 146, 40));

        btnListar.setFont(textoComponentes);
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 353, 208, 40));

        lblFondoVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(lblFondoVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
        regSalud.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        daoReg.getTmodel().setColumnCount(0);
        daoReg.getTmodel().setRowCount(0);
        daoReg.listarIncidencias();
        tblIncidencias.setModel(daoReg.getTmodel());
    }//GEN-LAST:event_btnListarActionPerformed

    private void txtPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteActionPerformed
        
    }//GEN-LAST:event_txtPacienteActionPerformed

    private void txtPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPacienteKeyReleased
        String cadenaFilt = txtPaciente.getText() + "%";
        daoReg.setNomPac(cadenaFilt);
        daoReg.getTmodel().setColumnCount(0);
        daoReg.getTmodel().setRowCount(0);
        daoReg.filtrarIncidencia();
        tblIncidencias.setModel(daoReg.getTmodel());
    }//GEN-LAST:event_txtPacienteKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIncidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIncidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIncidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIncidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIncidencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondoVerde;
    private javax.swing.JLabel lblIncCenEnf;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JTable tblIncidencias;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
