/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pantallas;

import clases.Conex;
import clases.Datos;
import clases.Hash;
import clases.UsuarioActual;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author joelfc
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public FrmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnCfg.setVisible(false);
        try {
            InetAddress addr = InetAddress.getByName(Conex.getInstance().getServer());
            if(addr.isReachable(3000)){
                btnLogin.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(this, "No se puede conectar con el Servidor");
            }
        } catch (UnknownHostException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        lblClave = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        btnCfg = new javax.swing.JButton();
        lblActivaCFG = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClave.setText("CLAVE");
        getContentPane().add(lblClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPassword.setText("PASSWORD");
        lblPassword.setToolTipText("");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtClave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 150, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPassword.setToolTipText("");
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 150, -1));

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setText("INICIAR SESION");
        btnLogin.setToolTipText("");
        btnLogin.setEnabled(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 40));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, 40));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoRojo2.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 200, 230));

        btnCfg.setText("CFG");
        btnCfg.setActionCommand("CFG");
        getContentPane().add(btnCfg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblActivaCFG.setToolTipText("");
        lblActivaCFG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActivaDesact(evt);
            }
        });
        getContentPane().add(lblActivaCFG, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 0, 40, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -30, 490, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Connection cone = Conex.getInstance().getConnection();
        String cadSha1;
        Statement stm;
        try {
            stm = cone.createStatement();
            String cadena = new String(txtPassword.getPassword());
            cadena = Hash.sha1(cadena);
            ResultSet rs = stm.executeQuery("select * from usuarios where clave='" +txtClave.getText() + "' and password= '"+ cadena+"'");
            if(rs.next()){
                Datos.idusuario=rs.getInt("idusuario");
                Datos.nombre = rs.getString("nombre");
                Datos.modPac = rs.getInt("mpacientes");
                Datos.modFarm = rs.getInt("mfarmacia");
                Datos.modControlEnf = rs.getInt("mctrlenf");
                Datos.modbenefa = rs.getInt("mbenefactores");
                Datos.modInventario = rs.getInt("minventario");   
                Datos.modUsuarios = rs.getInt("musuarios");
                FrmPrincipal ppal = new FrmPrincipal();
                ppal.setVisible(true);
                UsuarioActual.setUsuarioActual(txtClave.getText());
                System.out.println("Login: "+UsuarioActual.getUsuarioActual());
                this.setVisible(false);
            } else{
                JOptionPane.showMessageDialog(this, "usuario o Password inválido");
            }           
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
       
            
    }//GEN-LAST:event_btnLoginActionPerformed

    private void ActivaDesact(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActivaDesact
        // TODO add your handling code here:
        btnCfg.setVisible(!btnCfg.isVisible());
    }//GEN-LAST:event_ActivaDesact
      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCfg;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblActivaCFG;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtClave;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
