/*
 * Nombre del autor: Iván Ruiz Ramírez
                     Jose Luis Terraza Cortés
                     Dámaso Valdés Rosales
 * Fecha de creación: 2017/01/31
 * Nombre del proyecto: casaDescanso
 * Nombre del módulo: centralDeEnfermería
 * Breve descripción del contenido: pantalla que contiene la lista del personal de enfermería con su filtro.
 */
package pantallas;

import clases.DAOEnfermeras;
import static pantallas.frmEnfermeras.frmEnf;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;

/**
 *
 * @author IvanR
 */
public class frmListEnf extends javax.swing.JFrame {

    /**
     * Creates new form frmTablaEnf
     */
    public frmListEnf() {
        initComponents();
        skin1();
    }
    DAOEnfermeras daoEnf = new DAOEnfermeras();
    
    public void skin1(){
        Dimension dmnBtn = new Dimension(130, 50); //130, 50
        btnRegresar.setSize(dmnBtn);
        lblListEnf.setText(lblListEnf.getText().toUpperCase());
        lblNombreEnfermera.setText(lblNombreEnfermera.getText().toUpperCase());
        btnRegresar.setText(btnRegresar.getText().toUpperCase());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonalEnf = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        lblListEnf = new javax.swing.JLabel();
        lblNombreEnfermera = new javax.swing.JLabel();
        txtNombreEnfermera = new javax.swing.JTextField();
        lblFondoVerde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPersonalEnf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPersonalEnf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonalEnfMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPersonalEnf);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, 1007, 440));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 554, 129, 40));

        lblListEnf.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblListEnf.setText("Lista de personal");
        getContentPane().add(lblListEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 21, -1, -1));

        lblNombreEnfermera.setText("Nombre de personal:");
        getContentPane().add(lblNombreEnfermera, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 76, -1, -1));

        txtNombreEnfermera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreEnfermeraKeyReleased(evt);
            }
        });
        getContentPane().add(txtNombreEnfermera, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 73, 160, -1));

        lblFondoVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(lblFondoVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
        frmEnf.setVisible(true);
        frmEnf.txtIdEnfermera.setText("");
        frmEnf.txtNombreEnfermera.setText("");
        frmEnf.txtApellidoPatEnf.setText("");
        frmEnf.txtApellidoMatEnf.setText("");
        frmEnf.txtEspecialidad.setText("");
        frmEnf.txtEstatus.setText("");
        frmEnf.txaDescrEstatus.setText("");
        frmEnf.ftfTelefonoEnf.setText("");
        frmEnf.txtCorreoEnf.setText("");
        frmEnf.btnEliminarEnf.setEnabled(false);
        frmEnf.btnModificarEnf.setEnabled(false);
        frmEnf.btnAgregarEnf.setEnabled(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tblPersonalEnfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonalEnfMouseClicked
        if (!SwingUtilities.isRightMouseButton(evt)) {
            DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            int index = tblPersonalEnf.getSelectedRow();
            TableModel model = tblPersonalEnf.getModel();
            String fechaIn = "";
            String fechaTerm = "";
            String id = model.getValueAt(index, 0).toString();
            String nombre = model.getValueAt(index, 1).toString();
            String apPat = model.getValueAt(index, 2).toString();
            String apMat = model.getValueAt(index, 3).toString();
            String esp = model.getValueAt(index, 4).toString();
            String tipoDeIng = model.getValueAt(index, 5).toString();
            if(model.getValueAt(index, 6) != null){
                fechaIn = model.getValueAt(index, 6).toString();
            }
            if(model.getValueAt(index, 7) != null){
                fechaTerm = model.getValueAt(index, 7).toString();
            }
            String estatus = model.getValueAt(index, 8).toString();
            String descrEstatus = model.getValueAt(index, 9).toString();
            String telefono = model.getValueAt(index, 10).toString();
            String correo = model.getValueAt(index, 11).toString();
            dispose();
            frmEnf.setVisible(true);
            frmEnf.txtIdEnfermera.setText(id);
            frmEnf.txtNombreEnfermera.setText(nombre);
            frmEnf.txtApellidoPatEnf.setText(apPat);
            frmEnf.txtApellidoMatEnf.setText(apMat);
            frmEnf.txtEspecialidad.setText(esp);
            frmEnf.cmbTipoDeIngreso.setSelectedItem(tipoDeIng);
            try {
                frmEnf.dchFechaIn.setDate(fmt.parse(fechaIn));
                frmEnf.dchFechaTerm.setDate(fmt.parse(fechaTerm));
            } catch (ParseException ex) {
                frmEnf.dchFechaIn.setDate(null);
                frmEnf.dchFechaTerm.setDate(null);
            }
            frmEnf.txtEstatus.setText(estatus);
            frmEnf.txaDescrEstatus.setText(descrEstatus);
            frmEnf.ftfTelefonoEnf.setText(telefono);
            frmEnf.txtCorreoEnf.setText(correo);
            frmEnf.btnEliminarEnf.setEnabled(true);
            frmEnf.btnModificarEnf.setEnabled(true);
            frmEnf.btnAgregarEnf.setEnabled(false);
        }

    }//GEN-LAST:event_tblPersonalEnfMouseClicked

    private void txtNombreEnfermeraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEnfermeraKeyReleased
        daoEnf.setNombreEnfermera(txtNombreEnfermera.getText() + "%");
        daoEnf.getTmodel().setColumnCount(0);
        daoEnf.getTmodel().setRowCount(0);
        daoEnf.filtrar();
        tblPersonalEnf.setModel(daoEnf.getTmodel());
    }//GEN-LAST:event_txtNombreEnfermeraKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListEnf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondoVerde;
    private javax.swing.JLabel lblListEnf;
    private javax.swing.JLabel lblNombreEnfermera;
    public javax.swing.JTable tblPersonalEnf;
    private javax.swing.JTextField txtNombreEnfermera;
    // End of variables declaration//GEN-END:variables
}
