/*
 * Nombre del autor: Iván Ruiz Ramírez
 * Fecha de creación: 2017/01/31
 * Nombre del proyecto: casaDescanso
 * Nombre del módulo: centralDeEnfermería
 * Breve descripción del contenido:Pantalla que debe de listar la cantidad de dosis de todos los pedidos de medicamentos que fueron autorizados,
 * y los muestra en base a la fecha del pedido y su tipo de cantidad.
 */
package pantallas;

import clases.DAOPedMed;
import static pantallas.frmPedMed.pedMed;
import java.awt.Dimension;
import java.awt.Font;

/**
 *
 * @author IvanR
 */
public class frmListPedMedGrup extends javax.swing.JFrame {

    /**
     * Creates new form frmListPedMedGrup
     */
    public frmListPedMedGrup() {
        initComponents();
        skin1();
    }
    DAOPedMed daoPed = new DAOPedMed();
    Font textoTitulos = new Font("Tahoma",Font.BOLD,24);
    Font textoComponentes = new Font("Tahoma",Font.BOLD,14);
    
    public void skin1(){
        Dimension dmnBtn = new Dimension(130, 50); //130, 50
        btnRegresar.setSize(dmnBtn);
        lblListPedMedGrup.setText(lblListPedMedGrup.getText().toUpperCase());
        btnRegresar.setText(btnRegresar.getText().toUpperCase());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListGrup = new javax.swing.JTable();
        lblListPedMedGrup = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblFondoVerde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblListGrup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblListGrup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListGrupMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListGrup);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, 832, 377));

        lblListPedMedGrup.setFont(textoTitulos);
        lblListPedMedGrup.setText("Lista de cantidad por medicamento (Grupales)");
        getContentPane().add(lblListPedMedGrup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, -1, -1));

        btnRegresar.setFont(textoComponentes);
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 441, 167, 40));

        lblFondoVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(lblFondoVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
        pedMed.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tblListGrupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListGrupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblListGrupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListPedMedGrup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListPedMedGrup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListPedMedGrup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListPedMedGrup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListPedMedGrup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondoVerde;
    private javax.swing.JLabel lblListPedMedGrup;
    public javax.swing.JTable tblListGrup;
    // End of variables declaration//GEN-END:variables
}
