/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pantallas;

import clases.Datos;
import javax.swing.JFrame;

/**
 *
 * @author joelfc
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public FrmPrincipal() {
        initComponents();
        mnuUserCtrl.setVisible(false);  
        mnuPacientes.setVisible(false);
        mnuFarmacia.setVisible(false);
        mnuBenefactores.setVisible(false);
        mnuInventario.setVisible(false);
        mnuCtrlEnf.setVisible(false);
        if(Datos.modPac>0)
          mnuPacientes.setVisible(true);
        if(Datos.modFarm>0)
           mnuFarmacia.setVisible(true);
        if(Datos.modbenefa>0)
        mnuBenefactores.setVisible(true);
        if(Datos.modInventario>0)
           mnuInventario.setVisible(true);
        if(Datos.modControlEnf>0)
            mnuCtrlEnf.setVisible(true);
        if(Datos.modUsuarios>0)
         mnuUserCtrl.setVisible(true);
        
        
          
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserActual = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPacientes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuIngreEgre = new javax.swing.JMenuItem();
        mnuFarmacia = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        mnuCtrlEnf = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        mnuBenefactores = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        mnuInventario = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnuUserCtrl = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("La Sagrada Familia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 490, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Casa de descanso");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        txtUserActual.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtUserActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVerdeAzucena.png"))); // NOI18N
        getContentPane().add(txtUserActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 890));

        jMenuBar1.setAlignmentY(10.0F);
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        mnuPacientes.setText("Pacientes");
        mnuPacientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem2.setText("Control");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuPacientes.add(jMenuItem2);

        jMenuItem3.setText("Responsables");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuPacientes.add(jMenuItem3);

        mnuIngreEgre.setText("Ingresos/Egresos");
        mnuIngreEgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIngreEgreActionPerformed(evt);
            }
        });
        mnuPacientes.add(mnuIngreEgre);

        jMenuBar1.add(mnuPacientes);

        mnuFarmacia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mnuFarmacia.setText("Farmacia");
        mnuFarmacia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnuFarmacia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem5.setText("Entradas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuFarmacia.add(jMenuItem5);

        jMenuItem6.setText("Registro Productos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuFarmacia.add(jMenuItem6);

        jMenuItem8.setText("Asignacion");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnuFarmacia.add(jMenuItem8);

        jMenuBar1.add(mnuFarmacia);

        mnuCtrlEnf.setText("ControlEnf");
        mnuCtrlEnf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem9.setText("Personal");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mnuCtrlEnf.add(jMenuItem9);

        jMenuItem10.setText("Registro de Salud");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        mnuCtrlEnf.add(jMenuItem10);

        jMenuItem11.setText("Pedido Medicamentos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        mnuCtrlEnf.add(jMenuItem11);

        jMenuItem14.setText("Asignacion Pacientes");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        mnuCtrlEnf.add(jMenuItem14);

        jMenuBar1.add(mnuCtrlEnf);

        mnuBenefactores.setText("Benefactores");
        mnuBenefactores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem1.setText("Control");
        mnuBenefactores.add(jMenuItem1);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Donaciones");
        mnuBenefactores.add(jCheckBoxMenuItem1);

        jMenuBar1.add(mnuBenefactores);

        mnuInventario.setText("Inventario");
        mnuInventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem15.setText("Control");
        mnuInventario.add(jMenuItem15);

        jMenuBar1.add(mnuInventario);

        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mnuUserCtrl.setText("Control");
        mnuUserCtrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUserCtrlActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuUserCtrl);

        jMenuItem12.setText("Cambio Pwd");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        mnuUsuarios.add(jMenuItem12);

        jMenuBar1.add(mnuUsuarios);

        mnuSalir.setText("Salir");
        mnuSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem13.setText("Salir");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        mnuSalir.add(jMenuItem13);

        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        FrmCambioPwd fpwd = new FrmCambioPwd();
        fpwd.setVisible(true);

    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void mnuUserCtrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUserCtrlActionPerformed
         FrmUsuarios fusr = new FrmUsuarios();
         fusr.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
         fusr.setVisible(true);
  //         this.setVisible(false);
    }//GEN-LAST:event_mnuUserCtrlActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        frmAsigPaciente frmap = new frmAsigPaciente();
        frmap.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frmap.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FrmPacientes fpac = new FrmPacientes();
        fpac.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        fpac.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmPacientes2 resp = new FrmPacientes2();
        resp.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        resp.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnuIngreEgreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIngreEgreActionPerformed
      FrmHistorial_Ingresos_Egresos ingre = new FrmHistorial_Ingresos_Egresos();
      ingre.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
      ingre.setVisible(true);
    }//GEN-LAST:event_mnuIngreEgreActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        frmEntrada frme = new frmEntrada();
        frme.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frme.setVisible(true);
       //dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        frmProducto frmp = new frmProducto();
        frmp.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frmp.setVisible(true);
        //dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        frmAsignacion frma = new frmAsignacion();
        frma.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frma.setVisible(true);
        //dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        frmEnfermeras frme = new frmEnfermeras();
        frme.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frme.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        frmRegSaludPac frmrsp = new frmRegSaludPac();
        frmrsp.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frmrsp.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        frmPedMed frmpm = new frmPedMed();
        frmpm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frmpm.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu mnuBenefactores;
    private javax.swing.JMenu mnuCtrlEnf;
    private javax.swing.JMenu mnuFarmacia;
    private javax.swing.JMenuItem mnuIngreEgre;
    private javax.swing.JMenu mnuInventario;
    private javax.swing.JMenu mnuPacientes;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenuItem mnuUserCtrl;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JLabel txtUserActual;
    // End of variables declaration//GEN-END:variables
}
