/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import clases.Conex;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author JP
 */
public class frmReporteCompra extends javax.swing.JFrame {

    /**
     * Creates new form frmReporteCompra
     */
    public frmReporteCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenerarReporte = new javax.swing.JButton();
        jdcInicio = new com.toedter.calendar.JDateChooser();
        jdcFin = new com.toedter.calendar.JDateChooser();
        cmbTipoEntrada = new javax.swing.JComboBox();
        lblTipoEntrada = new javax.swing.JLabel();
        lblReporte = new javax.swing.JLabel();
        lblInicioReporte = new javax.swing.JLabel();
        lblFinReporte = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerarReporte.setText("GENERAR REPORTE");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 40));
        getContentPane().add(jdcInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 140, -1));
        getContentPane().add(jdcFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 140, -1));

        cmbTipoEntrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ASIGNADO", "COMPRADO", "DONADO" }));
        getContentPane().add(cmbTipoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 140, -1));

        lblTipoEntrada.setText("TIPO DE ENTRADA");
        getContentPane().add(lblTipoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lblReporte.setText("REPORTES DE ENTRADA");
        getContentPane().add(lblReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblInicioReporte.setText("INICIO REPORTE");
        getContentPane().add(lblInicioReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        lblFinReporte.setText("FIN REPORTE");
        getContentPane().add(lblFinReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
        HashMap Parametros = new HashMap();
        System.out.println(fmt.format(jdcInicio.getDate()));
        Parametros.put("Tipo_Entrada", cmbTipoEntrada.getSelectedItem().toString());
        Parametros.put("Inicio_Reporte", fmt.format(jdcInicio.getDate()));
        Parametros.put("Fin_Reporte", fmt.format(jdcFin.getDate()));
        System.out.println(Parametros);
        try{
            String path = "C:\\Users\\mikya_000\\Desktop\\CasaDescansov4\\CasaDescanso\\src\\pantallas\\ReporteCompra.jrxml";

            JasperReport reporteJasper = JasperCompileManager.compileReport(path);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, Parametros, Conex.getInstance().getConnection());
            JasperViewer.viewReport(mostrarReporte,false);
        } catch (JRException ex) {
            Logger.getLogger(pantallas.frmProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        frmEntrada fe = new frmEntrada();
        fe.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox cmbTipoEntrada;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JDateChooser jdcFin;
    private com.toedter.calendar.JDateChooser jdcInicio;
    private javax.swing.JLabel lblFinReporte;
    private javax.swing.JLabel lblInicioReporte;
    private javax.swing.JLabel lblReporte;
    private javax.swing.JLabel lblTipoEntrada;
    // End of variables declaration//GEN-END:variables
}
