/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import clases.Conex;
import clases.DaoTipo;
import clases.Tipo;
import java.awt.Font;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel Preciado Valerio el frame contiene todas las invocaciones de
 * metodos para el Frame Tipo.
 */
public class frmTipo extends javax.swing.JFrame {
    int buscar = 0;
    private void skin() {
        Font textTitulo = new Font("Tahoma", Font.BOLD, 24);
        Font textComponente = new Font("Tahoma", Font.BOLD, 14);
        lblTipoProd.setFont(textTitulo);
        lblTipoProducto.setFont(textComponente);
        txtTipoProducto.setFont(textComponente);
        btnAgregar.setFont(textComponente);
        btnBuscar.setFont(textComponente);
        btnEliminar.setFont(textComponente);
        btnListarParecidos.setFont(textComponente);
        btnModificar.setFont(textComponente);
        btnRegresar.setFont(textComponente);
    }

    /**
     * Creates new form frmTipo
     */
    public frmTipo() {
        initComponents();
        skin();
        DaoTipo da = new DaoTipo();
        da.setTipo(txtTipoProducto.getText());
        tblTipo.setModel(da.listar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipoProd = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblTipoProducto = new javax.swing.JLabel();
        txtTipoProducto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnListarParecidos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipo = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTipoProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTipoProd.setText("TIPO DE PRODUCTO");
        getContentPane().add(lblTipoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, -1, -1));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 339, -1, 40));
        btnAgregar.getAccessibleContext().setAccessibleName("");

        btnModificar.setText("MODIFICAR");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, 40));
        btnModificar.getAccessibleContext().setAccessibleName("");

        btnEliminar.setText("ELIMINAR");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, 40));
        btnEliminar.getAccessibleContext().setAccessibleName("");

        lblTipoProducto.setText("TIPO DE PRODUCTO");
        getContentPane().add(lblTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtTipoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTipoProductoKeyReleased(evt);
            }
        });
        getContentPane().add(txtTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 130, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, 40));

        btnListarParecidos.setText("LISTAR PARECIDOS");
        btnListarParecidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarParecidosActionPerformed(evt);
            }
        });
        getContentPane().add(btnListarParecidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 88, -1, 40));

        tblTipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTipoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTipo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 134, 391, 187));

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 339, -1, 40));
        btnRegresar.getAccessibleContext().setAccessibleName("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Tipo t1 = new Tipo();
        DaoTipo da2 = new DaoTipo();
        da2.setTipo(txtTipoProducto.getText());
        if (da2.agregar() == true) {
            JOptionPane.showMessageDialog(rootPane, "Registro agregado");
            txtTipoProducto.setText("");
            btnListarParecidos.doClick();

        } else {
            JOptionPane.showMessageDialog(rootPane, "No se inserto");

        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Tipo t2 = new Tipo();
        DaoTipo da = new DaoTipo();
        da.setIdTipo(buscar);
        da.setTipo(txtTipoProducto.getText());

        // btnListar.doClick();
        if (da.modificar()) {
            JOptionPane.showMessageDialog(rootPane, "se ha modificado el registro");
            txtTipoProducto.setText("");
            btnListarParecidos.doClick();
            btnEliminar.setEnabled(false);
            btnModificar.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(rootPane, "No se modifico");
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Tipo t3 = new Tipo();
        DaoTipo da = new DaoTipo();
        da.setTipo(txtTipoProducto.getText());
//        da.setTipo(((String)cmbExistentes.getSelectedItem().toString()));
        if (da.eliminar() == true) {
            JOptionPane.showMessageDialog(rootPane, "Se elimino el registro");
            txtTipoProducto.setText("");
            btnListarParecidos.doClick();
            btnEliminar.setEnabled(false);
            btnModificar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se elimino el registro");
        }
        // btnListar.doClick();


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarParecidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarParecidosActionPerformed
        DaoTipo da = new DaoTipo();
        da.setTipo(txtTipoProducto.getText());
        txtTipoProducto.setText("");
        tblTipo.setModel(da.listar());
    }//GEN-LAST:event_btnListarParecidosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DaoTipo d5 = new DaoTipo();
        String tipo;
        tipo = null;
        d5.setTipo(txtTipoProducto.getText());
        Connection con = Conex.getInstance().getConnection();
        String sql = "{call sp_tip_lis(?)}";
        try {
            CallableStatement stm = con.prepareCall(sql);
            stm.setString(1, d5.getTipo());
            ResultSet rs = stm.executeQuery();
            if (rs.next()) {
                buscar = (rs.getInt("idTipo"));
                tipo = (rs.getString("tipo"));

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: El nombre no existe.");
        }
        if (d5.buscar()) {
            txtTipoProducto.setText(d5.getTipo());
            JOptionPane.showMessageDialog(rootPane, "El producto exite");
            btnEliminar.setEnabled(true);
            btnModificar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Producto no encontrado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTipoMouseClicked
        int filaSeleccionada = tblTipo.getSelectedRow();
        int columna = 0;
        buscar = Integer.parseInt((String) tblTipo.getValueAt(filaSeleccionada, columna));
        txtTipoProducto.setText((String) tblTipo.getModel().getValueAt(filaSeleccionada, columna + 1));
        btnEliminar.setEnabled(true);
        btnModificar.setEnabled(true);
    }//GEN-LAST:event_tblTipoMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        frmProducto fp = new frmProducto();
        fp.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtTipoProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoProductoKeyReleased
        txtTipoProducto.setText(txtTipoProducto.getText().toUpperCase());
    }//GEN-LAST:event_txtTipoProductoKeyReleased

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListarParecidos;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTipoProd;
    private javax.swing.JLabel lblTipoProducto;
    private javax.swing.JTable tblTipo;
    private javax.swing.JTextField txtTipoProducto;
    // End of variables declaration//GEN-END:variables
}
