/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pantallas;

import clases.DaoUsuario;
import clases.Hash;
import clases.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author joelfc
 */
public class FrmUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form frmUsuarios
     */
    public FrmUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApPaterno = new javax.swing.JTextField();
        txtApMaterno = new javax.swing.JTextField();
        chkPacientes = new javax.swing.JCheckBox();
        chkFarmacia = new javax.swing.JCheckBox();
        chkCtrlEnf = new javax.swing.JCheckBox();
        chkBenefactores = new javax.swing.JCheckBox();
        chkInventario = new javax.swing.JCheckBox();
        chkPersMed = new javax.swing.JCheckBox();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkusuarios = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CLAVE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 61, -1, -1));

        txtClave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 58, 171, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 107, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("AP. PATERNO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 148, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("AP. MATERNO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 182, -1, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 104, 171, -1));

        txtApPaterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 145, 171, -1));

        txtApMaterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 179, 168, -1));

        chkPacientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkPacientes.setText("PACIENTES");
        getContentPane().add(chkPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        chkFarmacia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkFarmacia.setText("FARMACIA");
        getContentPane().add(chkFarmacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 281, -1, -1));

        chkCtrlEnf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkCtrlEnf.setText("CTRL ENFERMERIA");
        chkCtrlEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCtrlEnfActionPerformed(evt);
            }
        });
        getContentPane().add(chkCtrlEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        chkBenefactores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkBenefactores.setText("BENEFACTORES");
        getContentPane().add(chkBenefactores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        chkInventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkInventario.setText("INVENTARIO");
        getContentPane().add(chkInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 309, -1, -1));

        chkPersMed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkPersMed.setText("PERSONAL MEDICO");
        getContentPane().add(chkPersMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 309, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 364, -1, 41));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 100, 42));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, 41));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, 41));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("CONTROL DE USUARIOS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 11, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ASIGNAR ACCESO A MÓDULOS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 246, -1, -1));

        chkusuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkusuarios.setText("USUARIOS");
        getContentPane().add(chkusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
       DaoUsuario du = new DaoUsuario();
       du.setClave(txtClave.getText());
       du.setPassword(Hash.sha1(txtClave.getText()+"Pwd"));
       du.setNombre(txtNombre.getText());
       du.setAppat(txtApPaterno.getText());
       du.setApmat(txtApMaterno.getText());
       
       du.setmPacientes(chkPacientes.isSelected()?1:0);
       du.setmFarmacia(chkFarmacia.isSelected()?1:0);
       du.setmCtrlEnf(chkCtrlEnf.isSelected()?1:0);
       du.setmBenefactores(chkBenefactores.isSelected()?1:0);
       du.setmInventario(chkInventario.isSelected()?1:0);
       du.setmPersMed(chkPersMed.isSelected()?1:0);
       du.setmUsuarios(chkusuarios.isSelected()?1:0);
       if(du.agregar()){
           JOptionPane.showMessageDialog(this, "usuario Agregado");
           txtClave.setText("");
           txtNombre.setText("");
           txtApPaterno.setText("");
           txtApMaterno.setText("");
           chkBenefactores.setSelected(false);
           chkCtrlEnf.setSelected(false);
           chkFarmacia.setSelected(false);
           chkPacientes.setSelected(false);
           chkPersMed.setSelected(false);
           chkInventario.setSelected(false);
           chkusuarios.setSelected(false);
           txtClave.requestFocus();
       }else{
           JOptionPane.showMessageDialog(this, "Usuario no agregado\nFalta informacion de usuario");
       }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        DaoUsuario du = new DaoUsuario();
        du.setClave(txtClave.getText());
        Usuario  un = du.buscar();
       
        if(un!= null){
            txtNombre.setText(un.getNombre());
            txtApPaterno.setText(un.getAppat());
            txtApMaterno.setText(un.getApmat());
            chkPacientes.setSelected( un.getmPacientes()>0?true:false);
            chkFarmacia.setSelected( un.getmFarmacia()>0?true:false);
            chkBenefactores.setSelected( un.getmBenefactores()>0?true:false);
            chkCtrlEnf.setSelected( un.getmCtrlEnf()>0?true:false);
            chkInventario.setSelected( un.getmInventario()>0?true:false);
            chkPersMed.setSelected( un.getmPersMed()>0?true:false);
            chkusuarios.setSelected(un.getmUsuarios()>0?true:false);
            btnAgregar.setEnabled(false);
            btnModificar.setEnabled(true);
            
        }else{
            JOptionPane.showMessageDialog(this, "Usuario No existe");
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String cadClave=txtClave.getText();
        String cadNombre = txtNombre.getText();
        String cadApp = txtApPaterno.getText();
        String cadApm = txtApMaterno.getText();
        int mpac =(chkPacientes.isSelected()?1:0);
        int mfar =(chkFarmacia.isSelected()?1:0);
        int mben =(chkBenefactores.isSelected()?1:0);
        int mctlenf =(chkCtrlEnf.isSelected()?1:0);
        int minv =(chkInventario.isSelected()?1:0);
        int mpersm =(chkPersMed.isSelected()?1:0);
        int musr = (chkusuarios.isSelected()?1:0);
        DaoUsuario du = new DaoUsuario(cadClave,"",cadNombre, cadApp, cadApm, mpac, mfar, mben, mctlenf, minv,mpersm,musr );
        if(du.modificar()){
            txtClave.setText("");
            txtNombre.setText("");
           txtApPaterno.setText("");
           txtApMaterno.setText("");
           chkBenefactores.setSelected(false);
           chkCtrlEnf.setSelected(false);
           chkFarmacia.setSelected(false);
           chkPacientes.setSelected(false);
           chkPersMed.setSelected(false);
           chkInventario.setSelected(false);
           chkusuarios.setSelected(false);
           
            btnBuscar.setEnabled(true);
            btnAgregar.setEnabled(true);
            btnModificar.setEnabled(false);
            txtClave.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this, "Error al modificar usuario");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void chkCtrlEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCtrlEnfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCtrlEnfActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkBenefactores;
    private javax.swing.JCheckBox chkCtrlEnf;
    private javax.swing.JCheckBox chkFarmacia;
    private javax.swing.JCheckBox chkInventario;
    private javax.swing.JCheckBox chkPacientes;
    private javax.swing.JCheckBox chkPersMed;
    private javax.swing.JCheckBox chkusuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
